# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ka', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacient',
            name='user',
        ),
        migrations.AddField(
            model_name='pacient',
            name='ime',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
