# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ka', '0002_auto_20160609_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacient',
            name='aparat',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='maska',
        ),
        migrations.AddField(
            model_name='aparat',
            name='pacient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ka.Pacient'),
        ),
        migrations.AddField(
            model_name='maska',
            name='pacient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ka.Pacient'),
        ),
        migrations.AlterField(
            model_name='aparat',
            name='ponudnik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ka.Ponudnik'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='ponudnik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ka.Ponudnik'),
        ),
    ]
