# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ka', '0003_auto_20160609_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aparat',
            name='pacient',
        ),
        migrations.RemoveField(
            model_name='aparat',
            name='ponudnik',
        ),
        migrations.AddField(
            model_name='pacient',
            name='aparat',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='Aparat',
        ),
    ]
