# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 21:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ka', '0004_auto_20160610_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aparat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proizvajalec', models.CharField(max_length=120)),
                ('vrsta_terapije', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='maska',
            name='pacient',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='aparat',
        ),
        migrations.AddField(
            model_name='pacient',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Maska',
        ),
        migrations.AddField(
            model_name='aparat',
            name='pacient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ka.Pacient'),
        ),
    ]
