# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ka', '0005_auto_20160611_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maska',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pacient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ka.Pacient')),
            ],
        ),
        migrations.RemoveField(
            model_name='aparat',
            name='vrsta_terapije',
        ),
    ]
