# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ka', '0006_auto_20160612_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vprasanje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.CharField(max_length=250)),
                ('komentar_k_tekstu', models.TextField(null=True)),
                ('datum', models.DateTimeField(verbose_name='datum objave')),
            ],
        ),
        migrations.AlterField(
            model_name='aparat',
            name='proizvajalec',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='maska',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
