# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ka', '0007_auto_20160613_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anketa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Odgovor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='vprasanje',
            old_name='datum',
            new_name='datum_objave',
        ),
        migrations.AddField(
            model_name='vprasanje',
            name='aktiven',
            field=models.CharField(default='y', max_length=1),
        ),
    ]
