# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ka', '0009_auto_20160613_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vprasanje',
            name='datum_objave',
            field=models.DateTimeField(null=True, verbose_name='datum objave'),
        ),
    ]
